package crew

// Regression tests for tmux send-keys split behaviour.
//
// # Background
//
// gig-4040: --prompt text was pasted into a worker pane but Enter was never
// sent because SendCommand chained both operations in a single tmux invocation
// (\; syntax). Tmux processed the paste but dropped the Enter.
//
// gig-33ab: The same chained-invocation pattern survived in the shell script
// generated by buildWorkerStopScript in hooks/builtin.go.
//
// # Invariant
//
// Every code path that types text into a tmux pane MUST use two separate
// tmux process invocations:
//
//  1. tmux send-keys -t TARGET -l "TEXT"   (paste, literal flag)
//  2. tmux send-keys -t TARGET Enter       (submit, no -l flag)
//
// A single invocation that contains both "-l" and "Enter" is the broken
// pattern. These tests exist to catch any reintroduction of it.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// withFakeTmux installs a stub tmux binary that records every invocation as a
// space-joined argument string (one line per call) in a log file.  It patches
// PATH for the duration of the test via t.Setenv and returns a reader func.
// The stub always exits 0 so callers do not need a live tmux session.
func withFakeTmux(t *testing.T) func() []string {
	t.Helper()
	dir := t.TempDir()
	logFile := filepath.Join(dir, "calls.log")
	bin := filepath.Join(dir, "tmux")
	// Use /bin/sh for broadest compatibility.
	script := "#!/bin/sh\necho \"$*\" >> " + logFile + "\n"
	if err := os.WriteFile(bin, []byte(script), 0755); err != nil {
		t.Fatalf("create fake tmux binary: %v", err)
	}
	t.Setenv("PATH", dir+":"+os.Getenv("PATH"))

	return func() []string {
		data, _ := os.ReadFile(logFile)
		var lines []string
		for _, l := range strings.Split(strings.TrimSpace(string(data)), "\n") {
			if l != "" {
				lines = append(lines, l)
			}
		}
		return lines
	}
}

// sendKeysCalls filters recorded tmux invocations to only send-keys calls.
func sendKeysCalls(all []string) []string {
	var out []string
	for _, c := range all {
		if strings.HasPrefix(c, "send-keys ") {
			out = append(out, c)
		}
	}
	return out
}

// assertNoSingleCallCombinesTextAndEnter is the core regression assertion for
// gig-4040 and gig-33ab.
//
// The broken pattern is tmux command chaining within a single process invocation:
//
//	tmux send-keys -t TARGET -l TEXT ; send-keys -t TARGET Enter
//
// tmux interprets ";" as a command separator, so the caller passes it as an
// argument to exec.Command (Go) or escapes it as \; in a shell script.
// Either way, the Enter keystroke races with or is dropped after the paste.
//
// The fix: two separate os/exec invocations — the fake tmux stub records each
// as its own line, so the broken pattern is always detectable as a ";" on one line.
func assertNoSingleCallCombinesTextAndEnter(t *testing.T, calls []string) {
	t.Helper()
	for _, c := range calls {
		// Detect "; send-keys" chaining in a single tmux invocation.
		// Both Go's ";" argument and shell's "\;" appear here after echo "$*".
		if (strings.Contains(c, "; send-keys") || strings.Contains(c, `\; send-keys`)) &&
			strings.Contains(c, " -l ") && strings.Contains(c, "Enter") {
			t.Errorf(
				"regression (gig-4040/gig-33ab): single tmux invocation chains -l paste and Enter via \";\":\n  %q\n"+
					"Fix: two separate tmux process invocations — paste first, Enter second.",
				c,
			)
		}
	}
}

// TestSendCommandUsesTwoSeparateInvocations verifies that SendCommand never
// combines text paste and Enter in a single tmux call.
//
// This is the direct regression test for gig-4040, where SendCommand used
// tmux's ";" chaining (tmuxRun("send-keys", ..., ";", "send-keys", ..., "Enter"))
// and the Enter was dropped by tmux.
func TestSendCommandUsesTwoSeparateInvocations(t *testing.T) {
	calls := withFakeTmux(t)

	if err := SendCommand("jeff:test", "Read your task context"); err != nil {
		t.Fatalf("SendCommand returned error: %v", err)
	}

	got := sendKeysCalls(calls())

	// Must be exactly two send-keys calls: paste then Enter.
	if len(got) != 2 {
		t.Fatalf("want 2 send-keys calls, got %d: %v", len(got), got)
	}

	// First call: paste with -l (literal) flag.
	if !strings.Contains(got[0], " -l ") {
		t.Errorf("first call missing -l flag (paste call): %q", got[0])
	}

	// Second call: Enter key, no -l flag.
	if !strings.Contains(got[1], "Enter") {
		t.Errorf("second call missing Enter: %q", got[1])
	}
	if strings.Contains(got[1], " -l ") {
		t.Errorf("second call must not have -l flag (Enter only): %q", got[1])
	}

	assertNoSingleCallCombinesTextAndEnter(t, got)
}

// TestSendCommandWithMultiWordPrompt confirms the split behaviour holds for
// prompts containing spaces, which is the common --prompt use-case.
func TestSendCommandWithMultiWordPrompt(t *testing.T) {
	calls := withFakeTmux(t)

	prompt := "Read your task context using `gig show` for your task ID and begin working."
	if err := SendCommand("jeff:gig-33ab", prompt); err != nil {
		t.Fatalf("SendCommand: %v", err)
	}

	got := sendKeysCalls(calls())
	if len(got) != 2 {
		t.Fatalf("want 2 send-keys calls for multi-word prompt, got %d: %v", len(got), got)
	}
	assertNoSingleCallCombinesTextAndEnter(t, got)
}

// TestSendTextNeverSendsEnter confirms that SendText is a paste-only primitive:
// exactly one send-keys call with -l, and Enter must not appear anywhere.
// SendText is the building block for two-step delivery; it must never grow an
// implicit Enter.
func TestSendTextNeverSendsEnter(t *testing.T) {
	calls := withFakeTmux(t)

	if err := SendText("jeff:test", "some text"); err != nil {
		t.Fatalf("SendText: %v", err)
	}

	got := sendKeysCalls(calls())
	if len(got) != 1 {
		t.Fatalf("want 1 send-keys call from SendText, got %d: %v", len(got), got)
	}
	if !strings.Contains(got[0], " -l ") {
		t.Errorf("SendText call missing -l flag: %q", got[0])
	}
	if strings.Contains(got[0], "Enter") {
		t.Errorf("SendText must not send Enter: %q", got[0])
	}
}

// TestSendEnterNoLiteralFlag confirms that SendEnter sends exactly the Enter
// key and never uses the -l (literal) flag.  Sending Enter with -l would type
// the literal string "Enter" instead of pressing the key.
func TestSendEnterNoLiteralFlag(t *testing.T) {
	calls := withFakeTmux(t)

	if err := SendEnter("jeff:test"); err != nil {
		t.Fatalf("SendEnter: %v", err)
	}

	got := sendKeysCalls(calls())
	if len(got) != 1 {
		t.Fatalf("want 1 send-keys call from SendEnter, got %d: %v", len(got), got)
	}
	if !strings.Contains(got[0], "Enter") {
		t.Errorf("SendEnter call missing Enter: %q", got[0])
	}
	if strings.Contains(got[0], " -l ") {
		t.Errorf("SendEnter must not use -l flag: %q", got[0])
	}
}

// TestSendCommandInvariant is a table-driven sweep of the core invariant across
// different targets and command strings, including edge cases like empty string,
// strings containing "Enter", and strings with special characters.
func TestSendCommandInvariant(t *testing.T) {
	cases := []struct {
		name    string
		target  string
		command string
	}{
		{"simple", "jeff:gig-1234", "hello world"},
		{"contains-enter-word", "jeff:gig-1234", "Enter the task context"},
		{"special-chars", "jeff:gig-1234", "cat /tmp/foo && grep -n 'bar'"},
		{"backticks", "jeff:gig-1234", "Read your task via `gig show gig-1234`"},
		{"multiline-like", "jeff:gig-1234", "line one\nline two"},
		{"empty", "jeff:gig-1234", ""},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			calls := withFakeTmux(t)

			if err := SendCommand(tc.target, tc.command); err != nil {
				t.Fatalf("SendCommand(%q): %v", tc.command, err)
			}

			got := sendKeysCalls(calls())
			if len(got) != 2 {
				t.Fatalf("want 2 send-keys calls, got %d: %v", len(got), got)
			}
			assertNoSingleCallCombinesTextAndEnter(t, got)
		})
	}
}

// TestDivertInterruptSettleDelay verifies that interruptSettleDelay returns
// agent-specific durations for the divert post-C-c settle window (gig-c6dd).
// Gemini's Ink/React TUI needs 4 s to fully exit the interrupted state; during
// the 2 s window used for other agents, pasted text is routed to the "Queued"
// buffer instead of the live input.
func TestDivertInterruptSettleDelay(t *testing.T) {
	cases := []struct {
		agent string
		want  time.Duration
	}{
		{"gemini", geminiInterruptSettleDelay},
		{"claude", defaultInterruptSettleDelay},
		{"", defaultInterruptSettleDelay},
		{"other-agent", defaultInterruptSettleDelay},
	}
	for _, tc := range cases {
		t.Run(tc.agent, func(t *testing.T) {
			got := interruptSettleDelay(tc.agent)
			if got != tc.want {
				t.Errorf("interruptSettleDelay(%q) = %v, want %v", tc.agent, got, tc.want)
			}
		})
	}
}

// TestDivertSendKeysSequence verifies the send-keys call sequence for the
// divert path: C-c interrupt, then paste + Enter (two separate invocations).
// This is a regression guard for gig-4040/gig-33ab applied to the divert path.
func TestDivertSendKeysSequence(t *testing.T) {
	cases := []struct {
		name    string
		agent   string
		content string
	}{
		{"claude-simple", "claude", "new direction for the task"},
		{"claude-multiword", "claude", "stop reading files and focus on the API instead"},
		{"gemini-simple", "gemini", "new direction for the task"},
		{"gemini-multiword", "gemini", "stop reading files and focus on the API instead"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			calls := withFakeTmux(t)

			// Simulate the divert sequence: interrupt then deliver.
			if err := SendInterrupt("jeff:gig-c6dd"); err != nil {
				t.Fatalf("SendInterrupt: %v", err)
			}
			if err := sendCommandForSession("jeff:gig-c6dd", tc.content, tc.agent); err != nil {
				t.Fatalf("sendCommandForSession: %v", err)
			}

			got := sendKeysCalls(calls())

			// Expect exactly 3 send-keys calls: C-c, paste, Enter.
			if len(got) != 3 {
				t.Fatalf("want 3 send-keys calls (C-c, paste, Enter), got %d: %v", len(got), got)
			}

			// First call: C-c interrupt.
			if !strings.Contains(got[0], "C-c") {
				t.Errorf("first call must be C-c interrupt, got: %q", got[0])
			}

			// Second call: paste with -l flag.
			if !strings.Contains(got[1], " -l ") {
				t.Errorf("second call missing -l flag (paste): %q", got[1])
			}

			// Third call: Enter key, no -l flag.
			if !strings.Contains(got[2], "Enter") {
				t.Errorf("third call missing Enter: %q", got[2])
			}
			if strings.Contains(got[2], " -l ") {
				t.Errorf("third call must not have -l flag: %q", got[2])
			}

			assertNoSingleCallCombinesTextAndEnter(t, got)
		})
	}
}

// TestSendCommandWithDelayGeminiCase covers gig-906c: Gemini CLI's Ink/React TUI
// processes keyboard input asynchronously, so the default 100 ms delay in
// SendCommand is not enough — the Enter keypress arrives before Gemini has
// committed the pasted text to its input buffer, causing the message to sit
// unsent in the chat bar.
//
// The fix: sendCommandForSession uses SendCommandWithDelay(500ms) for Gemini
// agents.  This test verifies that SendCommandWithDelay still satisfies the
// two-separate-invocations invariant (gig-4040) regardless of the delay value,
// so the Gemini path can never regress into the chained-invocation anti-pattern.
func TestSendCommandWithDelayGeminiCase(t *testing.T) {
	cases := []struct {
		name    string
		target  string
		command string
	}{
		{"simple", "jeff:gig-906c", "hello gemini"},
		{"with-spaces", "jeff:gig-906c", "read your task context and begin working"},
		{"special-chars", "jeff:gig-906c", "cat /tmp/foo && echo 'done'"},
		{"empty", "jeff:gig-906c", ""},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			calls := withFakeTmux(t)

			// Use geminiSendDelay to mirror what sendCommandForSession does.
			if err := SendCommandWithDelay(tc.target, tc.command, geminiSendDelay); err != nil {
				t.Fatalf("SendCommandWithDelay(%q): %v", tc.command, err)
			}

			got := sendKeysCalls(calls())

			// Must be exactly two send-keys calls: paste then Enter.
			if len(got) != 2 {
				t.Fatalf("want 2 send-keys calls for Gemini path, got %d: %v", len(got), got)
			}

			// First call: paste with -l (literal) flag.
			if !strings.Contains(got[0], " -l ") {
				t.Errorf("first call missing -l flag (paste call): %q", got[0])
			}

			// Second call: Enter key, no -l flag.
			if !strings.Contains(got[1], "Enter") {
				t.Errorf("second call missing Enter: %q", got[1])
			}
			if strings.Contains(got[1], " -l ") {
				t.Errorf("second call must not have -l flag (Enter only): %q", got[1])
			}

			assertNoSingleCallCombinesTextAndEnter(t, got)
		})
	}
}
