package hooks

import (
	"os"
	"os/exec"
	"strings"
	"testing"
)

func TestSyncOpenCodeGeneratesPlugin(t *testing.T) {
	dir := t.TempDir()
	ctx := HookContext{JeffHome: dir, TargetDir: dir}

	hooks := []*Hook{
		{
			Name:  "test-hook",
			Event: "SessionStart",
			Scripts: map[string]func(ctx HookContext) string{
				"opencode": func(ctx HookContext) string {
					return `  // [test-hook]
  parts.push("hello from test");`
				},
			},
		},
	}

	if err := syncOpenCode(hooks, dir, ctx); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(openCodePluginPath(dir))
	if err != nil {
		t.Fatal(err)
	}

	content := string(data)
	if !strings.Contains(content, "AUTO-GENERATED by jeff") {
		t.Fatal("missing header comment")
	}
	if !strings.Contains(content, "hello from test") {
		t.Fatal("missing hook snippet")
	}
	if !strings.Contains(content, "JeffHooksPlugin") {
		t.Fatal("missing plugin export")
	}
}

func TestSyncOpenCodeMultipleHooks(t *testing.T) {
	dir := t.TempDir()
	ctx := HookContext{JeffHome: dir, TargetDir: dir}

	hooks := []*Hook{
		{
			Name:  "hook-a",
			Event: "SessionStart",
			Scripts: map[string]func(ctx HookContext) string{
				"opencode": func(ctx HookContext) string {
					return `  // [hook-a]
  parts.push("aaa");`
				},
			},
		},
		{
			Name:  "hook-b",
			Event: "SessionStart",
			Scripts: map[string]func(ctx HookContext) string{
				"opencode": func(ctx HookContext) string {
					return `  // [hook-b]
  parts.push("bbb");`
				},
			},
		},
	}

	if err := syncOpenCode(hooks, dir, ctx); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(openCodePluginPath(dir))
	content := string(data)
	if !strings.Contains(content, "hook-a") || !strings.Contains(content, "hook-b") {
		t.Fatal("missing one or both hook snippets")
	}
}

func TestSyncOpenCodeEmptyRemovesFile(t *testing.T) {
	dir := t.TempDir()
	ctx := HookContext{JeffHome: dir, TargetDir: dir}

	// First create a plugin file.
	hooks := []*Hook{
		{
			Name:  "temp",
			Event: "SessionStart",
			Scripts: map[string]func(ctx HookContext) string{
				"opencode": func(ctx HookContext) string { return `parts.push("temp");` },
			},
		},
	}
	syncOpenCode(hooks, dir, ctx)

	// Now sync with no hooks.
	if err := syncOpenCode(nil, dir, ctx); err != nil {
		t.Fatal(err)
	}

	if _, err := os.Stat(openCodePluginPath(dir)); !os.IsNotExist(err) {
		t.Fatal("expected plugin file to be removed when no hooks")
	}
}

func TestSyncOpenCodeFullRegistry_ProducesValidPlugin(t *testing.T) {
	dir := t.TempDir()
	ctx := HookContext{
		JeffHome:        dir,
		TargetDir:       dir,
		Persona:         "jenko",
		TaskID:          "gig-test-123",
		OrchestratorID:  "orch-1",
		Repos:           []string{"backend", "frontend"},
		CheckpointPatterns: []string{"*.go", "*.ts"},
	}

	// Sync all builtin hooks.
	reg := DefaultRegistry()
	if err := syncOpenCode(reg.All(), dir, ctx); err != nil {
		t.Fatal(err)
	}

	pluginPath := openCodePluginPath(dir)
	data, err := os.ReadFile(pluginPath)
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)

	// Basic structural assertions.
	if !strings.Contains(content, "JeffHooksPlugin") {
		t.Error("missing plugin export")
	}
	if !strings.Contains(content, "session.created") {
		t.Error("missing session.created handler")
	}
	// Count braces as a rough syntax check.
	open := strings.Count(content, "{")
	close := strings.Count(content, "}")
	if open != close {
		t.Errorf("brace mismatch: %d opening vs %d closing", open, close)
	}
	// Count parens.
	po := strings.Count(content, "(")
	pc := strings.Count(content, ")")
	if po != pc {
		t.Errorf("paren mismatch: %d opening vs %d closing", po, pc)
	}
	// No process.exit snippets written inside the object literal (must be before return).
	if strings.Contains(content, "},\n    },\n\n      // process-exit hook") {
		t.Error("process.exit snippet appears inside returned object literal")
	}
	// const id is declared once per event block (session.created, session.idle).
	// That's valid — each block is a separate scope.
	if strings.Count(content, "const id = sessionID") > 2 {
		t.Error("const id redeclared more than expected (2 blocks × 1 declaration each)")
	}

	// Try to parse with bun if available (npx tsc requires @types/node).
	if _, err := exec.LookPath("bun"); err == nil {
		cmd := exec.Command("bun", pluginPath)
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Logf("bun parse (may fail if types unavailable): %s", string(out))
		} else {
			t.Logf("bun parsed plugin successfully")
		}
	}
}

func TestSyncOpenCodeSkipsNilSnippets(t *testing.T) {
	dir := t.TempDir()
	ctx := HookContext{JeffHome: dir, TargetDir: dir}

	hooks := []*Hook{
		{Name: "no-opencode", Scripts: map[string]func(ctx HookContext) string{}},
	}

	if err := syncOpenCode(hooks, dir, ctx); err != nil {
		t.Fatal(err)
	}

	// No snippets → file removed.
	if _, err := os.Stat(openCodePluginPath(dir)); !os.IsNotExist(err) {
		t.Fatal("expected no plugin file for hook without opencode script")
	}
}
