package hooks

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// openCodePluginPath returns the path for the generated OpenCode plugin.
func openCodePluginPath(targetDir string) string {
	return filepath.Join(targetDir, ".opencode", "plugins", "jeff-hooks.ts")
}

// syncOpenCode regenerates the combined OpenCode plugin file from enabled hooks.
// If no hooks have OpenCode snippets, the file is removed.
func syncOpenCode(enabledHooks []*Hook, targetDir string, ctx HookContext) error {
	var snippets []openCodeSnippet
	for _, h := range enabledHooks {
		gen := h.Scripts["opencode"]
		if gen == nil {
			continue
		}
		snippet := gen(ctx)
		if snippet != "" {
			snippets = append(snippets, openCodeSnippet{event: openCodeEventName(h), code: snippet})
		}
	}

	pluginPath := openCodePluginPath(targetDir)

	if len(snippets) == 0 {
		os.Remove(pluginPath)
		return nil
	}

	content := generateOpenCodePlugin(snippets)

	if err := os.MkdirAll(filepath.Dir(pluginPath), 0o755); err != nil {
		return fmt.Errorf("create opencode plugins dir: %w", err)
	}
	return os.WriteFile(pluginPath, []byte(content), 0o644)
}

type openCodeSnippet struct {
	event string
	code  string
}

func openCodeEventName(h *Hook) string {
	if h.OpenCodeEvent != "" {
		return h.OpenCodeEvent
	}
	switch h.Event {
	case "SessionStart":
		return "session.created"
	case "PostToolUse":
		return "tool.execute.after"
	case "Stop":
		return "process.exit"
	default:
		return h.Event
	}
}

// generateOpenCodePlugin creates the full TypeScript plugin file from snippets.
// It uses OpenCode's documented event and tool hook surfaces. No package.json
// is needed because OpenCode runs local TypeScript plugins with its runtime.
func generateOpenCodePlugin(snippets []openCodeSnippet) string {
	var sb strings.Builder
	sb.WriteString(`// AUTO-GENERATED by jeff — do not edit manually.
// Regenerated on jeff init / jeff pickup. Edit jeff.json to enable/disable hooks.
import { execFileSync, execSync } from "node:child_process";

export const JeffHooksPlugin = async ({ client }) => {
  const run = (command: string): string => {
    try {
      return execSync(command, { encoding: "utf-8" }).trim();
    } catch {
      return "";
    }
  };

  const runFile = (file: string, args: string[]): string => {
    try {
      return execFileSync(file, args, { encoding: "utf-8" }).trim();
    } catch {
      return "";
    }
  };

  const sessionID = (event: any): string =>
    event.properties?.info?.id ?? event.properties?.sessionID ?? event.properties?.session?.id ?? "";

  const inject = async (id: string, text: string): Promise<void> => {
    if (!id || !text) return;
    try {
      await client.session.prompt({
        path: { id },
        body: {
          noReply: true,
          parts: [{ type: "text", text }],
        },
      });
    } catch {
      // Context injection is best-effort and must not break the session.
    }
  };

  const exitHandlers: Array<() => void> = [];

  return {
    event: async ({ event }) => {
      if (event.type === "session.created") {
        const id = sessionID(event);
        const parts: string[] = [];
`)

	for _, s := range snippets {
		if s.event == "session.created" {
			sb.WriteString(s.code)
			sb.WriteString("\n")
		}
	}

	sb.WriteString(`        await inject(id, parts.filter(Boolean).join("\\n\\n"));
      }

      if (event.type === "session.idle") {
        const id = sessionID(event);
        const parts: string[] = [];
`)

	for _, s := range snippets {
		if s.event == "session.idle" {
			sb.WriteString(s.code)
			sb.WriteString("\n")
		}
	}

	sb.WriteString(`        await inject(id, parts.filter(Boolean).join("\\n\\n"));
      }

      if (event.type === "session.deleted") {
        // Session cleanup is handled by process-exit hooks because deleting a
        // session is not the same as closing the OpenCode process.
	      }
    },

    "tool.execute.after": async (input: any, output: any) => {
      const parts: string[] = [];
`)

	for _, s := range snippets {
		if s.event == "tool.execute.after" {
			sb.WriteString(s.code)
			sb.WriteString("\n")
		}
	}

	sb.WriteString(`      await inject(input.sessionID ?? "", parts.filter(Boolean).join("\\n\\n"));
    },
`)

	for _, s := range snippets {
		if s.event == "process.exit" {
			sb.WriteString("      // process-exit hook\n")
			sb.WriteString("      exitHandlers.push(() => {\n")
			sb.WriteString(s.code)
			sb.WriteString("\n      });\n")
		}
	}
	if hasOpenCodeEvent(snippets, "process.exit") {
		sb.WriteString("      process.once(\"exit\", () => { for (const handler of exitHandlers) handler(); });\n")
	}
	sb.WriteString("  };\n};\n")
	return sb.String()
}

func hasOpenCodeEvent(snippets []openCodeSnippet, event string) bool {
	for _, s := range snippets {
		if s.event == event {
			return true
		}
	}
	return false
}
