package hooks

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// openCodePluginPath returns the path for the generated OpenCode plugin.
func openCodePluginPath(targetDir string) string {
	return filepath.Join(targetDir, ".opencode", "plugins", "jeff-hooks.js")
}

// syncOpenCode regenerates the combined OpenCode plugin file from enabled hooks.
// If no hooks have OpenCode snippets, the file is removed.
func syncOpenCode(enabledHooks []*Hook, targetDir string, ctx HookContext) error {
	var snippets []string
	for _, h := range enabledHooks {
		if h.OpenCodeSnippet == nil {
			continue
		}
		snippet := h.OpenCodeSnippet(ctx)
		if snippet != "" {
			snippets = append(snippets, snippet)
		}
	}

	pluginPath := openCodePluginPath(targetDir)

	if len(snippets) == 0 {
		os.Remove(pluginPath)
		return nil
	}

	content := generateOpenCodePlugin(snippets)

	if err := os.MkdirAll(filepath.Dir(pluginPath), 0o755); err != nil {
		return fmt.Errorf("create opencode plugins dir: %w", err)
	}
	return os.WriteFile(pluginPath, []byte(content), 0o644)
}

// generateOpenCodePlugin creates the full JS plugin file from snippets.
func generateOpenCodePlugin(snippets []string) string {
	var sb strings.Builder
	sb.WriteString(`// AUTO-GENERATED by jeff — do not edit manually.
// Regenerated on jeff init / jeff pickup. Edit jeff.yaml to enable/disable hooks.
import { execSync } from "child_process";

export const JeffHooksPlugin = async ({ client }) => {
  return {
    event: async ({ event }) => {
      if (event.type !== "session.created") return;

      const sessionId = event.properties?.info?.id;
      if (!sessionId) return;

      const parts = [];

`)

	for _, s := range snippets {
		sb.WriteString(s)
		sb.WriteString("\n\n")
	}

	sb.WriteString(`      const context = parts.filter(Boolean).join("\\n\\n");
      if (!context) return;

      try {
        await client.session.prompt({
          path: { id: sessionId },
          body: {
            parts: [{ type: "text", text: context }],
          },
        });
      } catch {
        // silently skip if prompt fails
      }
    },
  };
};
`)
	return sb.String()
}
