package hooks

import (
	"os"
	"strings"
	"testing"
)

func TestSyncOpenCodeGeneratesPlugin(t *testing.T) {
	dir := t.TempDir()
	ctx := HookContext{JeffHome: dir, TargetDir: dir}

	hooks := []*Hook{
		{
			Name:  "test-hook",
			Event: "SessionStart",
			Scripts: map[string]func(ctx HookContext) string{
				"opencode": func(ctx HookContext) string {
					return `  // [test-hook]
  parts.push("hello from test");`
				},
			},
		},
	}

	if err := syncOpenCode(hooks, dir, ctx); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(openCodePluginPath(dir))
	if err != nil {
		t.Fatal(err)
	}

	content := string(data)
	if !strings.Contains(content, "AUTO-GENERATED by jeff") {
		t.Fatal("missing header comment")
	}
	if !strings.Contains(content, "hello from test") {
		t.Fatal("missing hook snippet")
	}
	if !strings.Contains(content, "JeffHooksPlugin") {
		t.Fatal("missing plugin export")
	}
}

func TestSyncOpenCodeMultipleHooks(t *testing.T) {
	dir := t.TempDir()
	ctx := HookContext{JeffHome: dir, TargetDir: dir}

	hooks := []*Hook{
		{
			Name:  "hook-a",
			Event: "SessionStart",
			Scripts: map[string]func(ctx HookContext) string{
				"opencode": func(ctx HookContext) string {
					return `  // [hook-a]
  parts.push("aaa");`
				},
			},
		},
		{
			Name:  "hook-b",
			Event: "SessionStart",
			Scripts: map[string]func(ctx HookContext) string{
				"opencode": func(ctx HookContext) string {
					return `  // [hook-b]
  parts.push("bbb");`
				},
			},
		},
	}

	if err := syncOpenCode(hooks, dir, ctx); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(openCodePluginPath(dir))
	content := string(data)
	if !strings.Contains(content, "hook-a") || !strings.Contains(content, "hook-b") {
		t.Fatal("missing one or both hook snippets")
	}
}

func TestSyncOpenCodeEmptyRemovesFile(t *testing.T) {
	dir := t.TempDir()
	ctx := HookContext{JeffHome: dir, TargetDir: dir}

	// First create a plugin file.
	hooks := []*Hook{
		{
			Name:  "temp",
			Event: "SessionStart",
			Scripts: map[string]func(ctx HookContext) string{
				"opencode": func(ctx HookContext) string { return `parts.push("temp");` },
			},
		},
	}
	syncOpenCode(hooks, dir, ctx)

	// Now sync with no hooks.
	if err := syncOpenCode(nil, dir, ctx); err != nil {
		t.Fatal(err)
	}

	if _, err := os.Stat(openCodePluginPath(dir)); !os.IsNotExist(err) {
		t.Fatal("expected plugin file to be removed when no hooks")
	}
}

func TestSyncOpenCodeSkipsNilSnippets(t *testing.T) {
	dir := t.TempDir()
	ctx := HookContext{JeffHome: dir, TargetDir: dir}

	hooks := []*Hook{
		{Name: "no-opencode", Scripts: map[string]func(ctx HookContext) string{}},
	}

	if err := syncOpenCode(hooks, dir, ctx); err != nil {
		t.Fatal(err)
	}

	// No snippets → file removed.
	if _, err := os.Stat(openCodePluginPath(dir)); !os.IsNotExist(err) {
		t.Fatal("expected no plugin file for hook without opencode script")
	}
}
